config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/demichie/IMEX_SfloW2D_v2:
      branch: master
      repo: https://github.com/demichie/IMEX_SfloW2D_v2
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/demichie/IMEX_SfloW2D_v2 git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-bronze-barnacle.sh
        container: qc.acc_paltry-puce-cheetah
  QC.Doc:
    repos:
      github.com/demichie/IMEX_SfloW2D_v2 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-platinum-binturong.sh
        container: qc.doc_muggy-buff-quoll
      github.com/demichie/IMEX_SfloW2D_v2 git:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-gamboge-ragdoll.sh
        container: qc.doc_jumpy-auburn-salamander
      github.com/demichie/IMEX_SfloW2D_v2 markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-emerald-caterpillar.sh
        container: qc.doc_gummy-apricot-turkey
  QC.Lic:
    repos:
      github.com/demichie/IMEX_SfloW2D_v2 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-bronze-kudu.sh
        container: qc.lic_frumpy-platinum-sheepdog
  QC.Met:
    repos:
      github.com/demichie/IMEX_SfloW2D_v2 cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-cinnamon-spitz.sh
        container: qc.met_scanty-carmine-dingo
  QC.Sec:
    repos:
      github.com/demichie/IMEX_SfloW2D_v2 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-lemon-setter.sh
        container: qc.sec_blurry-lemon-husky
  QC.Sty:
    repos:
      github.com/demichie/IMEX_SfloW2D_v2 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-khaki-heron.sh
        container: qc.sty_stinky-burgundy-audemer
      github.com/demichie/IMEX_SfloW2D_v2 hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-ochre-spoonbill.sh
        container: qc.sty_foggy-aqua-turtle
  QC.Ver:
    repos:
      github.com/demichie/IMEX_SfloW2D_v2 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-aquamarine-abyssinian.sh
        container: qc.ver_ugly-purple-gibbon
timeout: 5400
