config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/demichie/IMEX_SfloW2D_v2:
      branch: master
      repo: https://github.com/demichie/IMEX_SfloW2D_v2
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/demichie/IMEX_SfloW2D_v2 git:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-silver-bullfrog.sh
        container: qc.acc_smelly-chestnut-mastiff
  QC.Doc:
    repos:
      github.com/demichie/IMEX_SfloW2D_v2 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-alizarin-dragon.sh
        container: qc.doc_zippy-khaki-meerkat
      github.com/demichie/IMEX_SfloW2D_v2 git:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-rust-jaguar.sh
        container: qc.doc_tasty-copper-snake
      github.com/demichie/IMEX_SfloW2D_v2 markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-russet-frigatebird.sh
        container: qc.doc_randy-mauve-uguisu
  QC.Lic:
    repos:
      github.com/demichie/IMEX_SfloW2D_v2 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-aquamarine-discus.sh
        container: qc.lic_shaggy-blue-gibbon
  QC.Met:
    repos:
      github.com/demichie/IMEX_SfloW2D_v2 cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-mustard-labradoodle.sh
        container: qc.met_baggy-brown-wombat
  QC.Sec:
    repos:
      github.com/demichie/IMEX_SfloW2D_v2 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-periwinkle-bobcat.sh
        container: qc.sec_frumpy-denim-mau
  QC.Sty:
    repos:
      github.com/demichie/IMEX_SfloW2D_v2 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-brass-zorse.sh
        container: qc.sty_whiny-ruby-caiman
      github.com/demichie/IMEX_SfloW2D_v2 hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-harlequin-lobster.sh
        container: qc.sty_shaky-carmine-zebu
  QC.Ver:
    repos:
      github.com/demichie/IMEX_SfloW2D_v2 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-asparagus-guppy.sh
        container: qc.ver_sloppy-coral-antelope
timeout: 5400
