config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/demichie/IMEX_SfloW2D_v2:
      branch: master
      repo: https://github.com/demichie/IMEX_SfloW2D_v2
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/demichie/IMEX_SfloW2D_v2 git:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-dandelion-opossum.sh
        container: qc.acc_messy-plum-butterfly
  QC.Doc:
    repos:
      github.com/demichie/IMEX_SfloW2D_v2 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-corn-gar.sh
        container: qc.doc_woozy-goldenrod-kangaroo
      github.com/demichie/IMEX_SfloW2D_v2 git:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-olive-lynx.sh
        container: qc.doc_snappy-vermilion-bonobo
      github.com/demichie/IMEX_SfloW2D_v2 markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-magenta-cheetah.sh
        container: qc.doc_snazzy-sangria-peccary
  QC.Lic:
    repos:
      github.com/demichie/IMEX_SfloW2D_v2 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-sapphire-bordeaux.sh
        container: qc.lic_sleepy-crimson-iguana
  QC.Met:
    repos:
      github.com/demichie/IMEX_SfloW2D_v2 cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-orchid-quokka.sh
        container: qc.met_ugly-copper-greyhound
  QC.Sec:
    repos:
      github.com/demichie/IMEX_SfloW2D_v2 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-heliotrope-wasp.sh
        container: qc.sec_sleazy-aqua-dragonfly
  QC.Sty:
    repos:
      github.com/demichie/IMEX_SfloW2D_v2 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.beady-cinnabar-earwig.sh
        container: qc.sty_sleepy-silver-dodo
      github.com/demichie/IMEX_SfloW2D_v2 hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-sepia-squirt.sh
        container: qc.sty_hasty-myrtle-walrus
  QC.Ver:
    repos:
      github.com/demichie/IMEX_SfloW2D_v2 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-amaranth-heron.sh
        container: qc.ver_bluesy-magenta-coral
timeout: 5400
