config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/demichie/IMEX_SfloW2D_v2:
      branch: master
      repo: https://github.com/demichie/IMEX_SfloW2D_v2
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/demichie/IMEX_SfloW2D_v2 git:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-wheat-lynx.sh
        container: qc.acc_goopy-sangria-axolotl
  QC.Doc:
    repos:
      github.com/demichie/IMEX_SfloW2D_v2 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-jade-mau.sh
        container: qc.doc_squirrely-wisteria-bandicoot
      github.com/demichie/IMEX_SfloW2D_v2 git:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-gamboge-mandrill.sh
        container: qc.doc_surly-sapphire-bee
      github.com/demichie/IMEX_SfloW2D_v2 markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-apricot-gecko.sh
        container: qc.doc_gimpy-teal-lionfish
  QC.Lic:
    repos:
      github.com/demichie/IMEX_SfloW2D_v2 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-grey-axolotl.sh
        container: qc.lic_bumpy-denim-worm
  QC.Met:
    repos:
      github.com/demichie/IMEX_SfloW2D_v2 cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-ecru-woodpecker.sh
        container: qc.met_homely-mustard-weasel
  QC.Sec:
    repos:
      github.com/demichie/IMEX_SfloW2D_v2 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-pear-toad.sh
        container: qc.sec_gamy-turquoise-frise
  QC.Sty:
    repos:
      github.com/demichie/IMEX_SfloW2D_v2 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-tangerine-horse.sh
        container: qc.sty_randy-apricot-seahorse
      github.com/demichie/IMEX_SfloW2D_v2 hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-olivine-albatross.sh
        container: qc.sty_gamy-taupe-insect
  QC.Ver:
    repos:
      github.com/demichie/IMEX_SfloW2D_v2 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-salmon-scorpion.sh
        container: qc.ver_crabby-champagne-millipede
timeout: 5400
